name: samex_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: 0.4.2
  sqflite: 0.11.2+4
  path_provider: 0.4.1
  intl: 0.15.8
  fluttertoast: 2.1.1
  after_layout: 1.0.4
  connectivity: 0.3.1
  open_file: 1.1.1
  package_info: 0.3.2
  rxdart: 0.18.1
  event_bus: 1.0.1
  image_picker: 0.4.10
  cached_network_image: 0.5.0+1
  image: 2.0.4
  flutter_boost: 0.0.415
  barcode_scan: 0.0.8
#    path: ../Plugins/flutter_barcode_reader
  dio:
    path: ../Plugins/dio

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/login_background.png
  - assets/images/login_user.png
  - assets/images/login_password.png
  - assets/images/home_background.png
  - assets/images/home_message.png
  - assets/images/home_assets.png
  - assets/images/home_notification.png
  - assets/images/home_history.png
  - assets/images/home_order.png
  - assets/images/home_material.png
  - assets/images/home_meter.png
  - assets/images/task_xj.png
  - assets/images/task_pm.png
  - assets/images/task_cm.png
  - assets/images/order_no_sync.png
  - assets/images/order_no_handle.png
  - assets/images/order_error_sync.png
  - assets/images/task_detail_material.png
  - assets/images/task_detail_detail.png
  - assets/images/task_detail_task.png
  - assets/images/task_detail_person.png
  - assets/images/scan.png
  - assets/images/order_ing.png
  - assets/images/order_ing_red.png
  - assets/images/order_done.png
  - assets/images/order_daiyanshou.png
  - assets/images/order_pizhun.png
  - assets/images/order_daipizhun.png
  - assets/images/logout.png
  - assets/images/szsw.png

  fonts:
    - family: Miui
      fonts:
        - asset: assets/fonts/miui.ttf
  #  - images/a_dot_ham.jpeg

  module:
    androidPackage: com.hddz.samex_module
    iosBundleIdentifier: com.hddz.samex_module